### PR TITLE
Surround regex in parentheses for alternation

### PR DESCRIPTION
**Pull request by kitbs**
See issue https://github.com/ronanguilloux/IsoCodes/issues/108

### CODE REVIEW

**Comment by kitbs** [comment]
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #108

**Comment by ronanguilloux** [comment]
Thank you @kitbs, super nice improvment.
May I ask you to add some unit tests to illustrate such improvment with 2 additional uni tests cases: the ones you just gave us as an example are actually super accurate:

in `getValidValues()`:
```php
['CR0 3RL', 'GB'],
```

in `getInvalidValues()`:
```php
['anystuffbefore CR0 3RL anyjunkattheend', 'GB'],
```

**Comment by kitbs** [comment]
Great! I added a few other tests in there to keep things interesting. ;-)

**Comment by ronanguilloux** [comment]
Thanks for that

**Pull request merged**
