### PR TITLE
Traditional to short array syntax

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Since #24, this project require php >=5.4.

So we can now use the new array short syntax as defined on this change-log: http://php.net/manual/en/migration54.new-features.php

@stof just for advice, are you agree with that?

Regards.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Note: You should avoid @coveralls comments, it's very intrusive and we have already the information on PR state. ;-)

**Comment by Soullivaneuh** [comment]
@ronanguilloux I think this is good to merge.

Short syntax is the new way introduced since php 5.4. There is no reason to not use them.

**Comment by ronanguilloux** [comment]
Interesting proposal as it is a typical discussion, appearing in many projects since PHP 5.4 bring us the `[]` syntax! Unfortunately, it neither bring any quality assurance nor it give better value to the code :-|

- in [Drupal 8](https://www.drupal.org/node/2135291) same PR was closed and reduced as a policy statement about D8 (but not even D7) code standards. Any big-patch was excluded, due of many exisiting PR being immediately backward-compatibility broken in case such patch became merged.
- in [Symfony 2 (not 3)](https://github.com/symfony/symfony-docs/issues/4408) this was closed as rejected, more or less for the same reasons
- In [Faker](https://github.com/fzaninotto/Faker), such short array syntax [is not used so far](http://squizlabs.github.io/PHP_CodeSniffer/analysis/fzaninotto/Faker/), and should probably not be for the same existing-PR-not-to-be-broken issue  

Conclusions so far, & RFC:
-  Using array() doesn't make your code/documentation outdated at all. This is not a "traditional" array, it's just one of both existing alternatives - important clarification ;-)
- There is absolutely no runtime problem with the existing syntax.

Side comment:
- Usually, such mega patch attempt like this has no benefit other than breaking hundreds of existing patches in the queue. Fortunately, the are no existing PR is involved so far, but we always have to keep this in mind.

This is open to any comments.

**Comment by Soullivaneuh** [comment]
You said it on your comment, similar PR was rejected do to another PR break because of a "big patch". It's understandable and it would be preferable to introduce short syntax one by one as the same time of features modifications.

> Fortunately, the are no existing PR is involved so far, but we always have to keep this in mind.

This exactly why I proposed this PR. Let's take the chance to get this new syntax every where before we can't because of lot of PR waiting. :+1: 

> in Symfony 2 (not 3) this was closed as rejected, more or less for the same reasons.

For that, but also because Symfony will still support PHP 5.3 for version 2. This could (I hope) change for Symfony 3.

> Using array() doesn't make your code/documentation outdated at all. This is not a "traditional" array, it's just one of both existing alternatives - important clarification ;-)

> There is absolutely no runtime problem with the existing syntax.

I agree. After all, it's just a coding style choice. Maybe this will be clarified later on other PSR (PHP 7?).

Personally, I prefer this new syntax because it's more clearer and readable (especially for unit testing data set) rather than always using the `array` keyword.

I think this was introduced especially to simplify code writing.

It's up to you to choose if you want to keep the traditional syntax. But I think the new syntax will be more used later on many projects.

**Comment by stof** [comment]
> For that, but also because Symfony will still support PHP 5.3 for version 2. This could (I hope) change for Symfony 3.

Given that Symfony 2.8 will be supported for 3 years starting in November, and that Symfony handles the support of multiple branches by merging branches together, Symfony will not switch until at least 3.5 years from now (usign a different syntax in 2.8 and 3.0 means that merging 2.8 into 3.x to propagate bug fixes would trigger conflicts all the time)

**Comment by Soullivaneuh** [comment]
@stof Oh, indeed. Didn't think about that.

We fortunately not have this problem here.

@ronanguilloux what should we decide?

**Comment by ronanguilloux** [comment]
Conclusions so far:
- it neither brings any quality assurance nor it gives better value to the code
- it's not a bugfix, and not a new feature either
- it doesn't address any particular issue

=> closed.
Thanks for you proposal, anyway ;-)

**Pull request closed without merging**
