### PR TITLE
Add Laravel 5 wrapper repository to readme

### PR DESCRIPTION
**Pull request by pixelpeter**
Add Laravel 5 wrapper repository to the readme

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Nice!

Maybe you could also add your package under the `suggest` section: https://github.com/ronanguilloux/IsoCodes/blob/master/composer.json#L34

**Comment by pixelpeter** [comment]
Done ;-)

**Comment by Soullivaneuh** [comment]
@ronanguilloux LGTM

**Comment by ronanguilloux** [comment]
@pixelpeter Sorry, I didn't mind your PR while adding your repo to the README.
Feel free to rebase on master and then I'll add your composer suggestion.

Cheers!

**Comment by pixelpeter** [comment]
@ronanguilloux Done the rebase. Please check if everything is OK.

**Comment by ronanguilloux** [comment]
Ouch, you didn't rebase on master, so you're now removing some recent changes. This PR cannot be merged.
Never mind, I'll add the composer.jon line by myself.
Thanks for that suggestion.

**Comment by pixelpeter** [comment]
@ronanguilloux 
Sorry, for that. This was my first rebase of a fork and I did it like it's described in several tutorials

```
git checkout add-laravel-wrapper-to-readme
git remote add upstream https://github.com/ronanguilloux/IsoCodes.git
git fetch upstream
git rebase upstream/master
git push origin add-laravel-wrapper-to-readme --force
```

**Pull request closed without merging**
