### PR TITLE
Remove deprecated strict option from PHPUnit

### LINKED ISSUE #20: Replace deprecated PHPUnit  `strict` option
PHPUnit versions have deprecated the `strict` option, thus this message is shown for every invocation:

`Deprecated configuration setting "strict" used`

See #13 and https://travis-ci.org/ronanguilloux/IsoCodes/jobs/59845136

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #20.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
HHVM seems to not be ready with your test suites. You should add it on allow_failures for the moment.

**Comment by ronanguilloux** [comment]
hhvm is not in cause, just Travis having some random chest pain.
=> accepted

**Comment by Soullivaneuh** [comment]
HHVM in cause or not, this always fail. Check out this job for example: https://travis-ci.org/ronanguilloux/IsoCodes/jobs/60603158

I maintain my advice about add it on allowed failures section.

**Comment by stof** [comment]
@Soullivaneuh there is a bug in PHPUnit 4.6.x phars on HHVM. I (hopefully) fixed the issue in PHPUnit yesterday so the next PHPUnit release should work again.

**Comment by Soullivaneuh** [comment]
@stof Hmm ok, I should got this new version on #23. This is why is working now. :+1:

**Pull request merged**
