### PR TITLE
Remove a useless computation of the string length

### PR DESCRIPTION
**Pull request by stof**
We already know that the string length is equal to ``$length`` because of the previous check

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by ronanguilloux** [comment]
#22 should fix the PHPUnit related issue in Travis:
May I ask you to fetch upstream (#22 was merged) first, then retry a commit+push?

**Comment by Soullivaneuh** [comment]
@stof please wait #23 to be merged.

**Comment by ronanguilloux** [comment]
#23 merged.

**Comment by ronanguilloux** [comment]
Thanks.

**Pull request merged**
